tap "homebrew/cask"

# Brews
brew "asdf"
brew "ctags"
brew "diff-so-fancy"
brew "grafana"
brew "git"
brew "htop"
brew "helm"
brew "hivemind"
brew "k9s"
brew "kube-ps1"
brew "kubectl"
brew "neovim"
brew "minikube"
brew "postgresql"
brew "reattach-to-user-namespace"
brew "redis"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "zsh"

# Casks
cask "font-hack-nerd-font"
cask "ngrok"
cask "visual-studio-code"
