#!/bin/sh

# Install xcode command line tools
if ! command -v xcode-select -p 1>/dev/null; then
  echo "Xcode command line tools already installed"
else
  echo "Installing xcode command line tools"
  xcode-select --install
fi

# Install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/homebrew/install/master/install)"
fi

if [ -f "$HOME/.Brewfile" ]; then
  echo "Running homebrew bundle"
  brew bundle --global
fi

if [ -d "$HOME/.iterm2" ]; then
  echo "Setting iTerm preference folder"
  defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
fi

if ! command -v asdf >/dev/null 2>&1; then
  if ! command -v which ruby >/dev/null 2>&1; then
    echo "Ruby already installed"
  else
    echo "Install asdf ruby"
    asdf plugin-add ruby "https://github.com/asdf-vm/asdf-ruby.git"
  fi
fi

# Run vim-plug
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:eiei0/dotfiles.git"
yadm branch --set-upstream-to origin/master

echo "\n\nBootstrap complete"
